services:
  - type: web
    name: solar-roof-analyzer
    env: node
    buildCommand: npm install
    startCommand: npx vercel dev
    envVars:
      - key: GOOGLE_SOLAR_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false